#!/bin/bash
if [ $# -lt 4 ]; then
    echo Usage: shaco-init host db usr passwd
    exit
fi
error() {
    echo -ne "\033[40;31;1m"
    echo -ne "$@"
    echo -ne "\033[0m"
}
info() {
    echo -ne "\033[40;32;1m"
    echo "$@"
    echo -ne "\033[0m"
}

error Are you sure to do this? [Y/N]
read Y
if [ $Y != "Y" ]; then
    exit
fi

DBSQL=game.sql
SQL=svn://192.168.1.200/quanzhi/program/server/trunk/sql/$DBSQL
HOST=$1 
DB=$2
USR=$3
PASSWD=$4

info 1. Init db [host:$HOST db:$DB user:$USR] 

svn export $SQL

expect<<EOF
spawn mysql -uroot -p
expect {
    "Enter password:" {
        send "root_dev\r"
        exp_continue
    } mysql> {
        send "show databases;\r"
        expect mysql> {send "create database $DB;\r"}
        expect mysql> {send "GRANT ALL PRIVILEGES ON $USR.* TO '$USR'@'%' IDENTIFIED BY '$PASSWD' WITH GRANT OPTION;\r"}
        expect mysql> {send "GRANT ALL PRIVILEGES ON $USR.* TO '$USR'@'localhost' IDENTIFIED BY '$PASSWD' WITH GRANT OPTION;\r"}
        expect mysql> {send "FLUSH PRIVILEGES;\r"}
        expect mysql> {send_user "\n"}
    } timeout {
        error "timeout\n"
    }
}
EOF

mysql -h$HOST -u$USR -p$PASSWD $DB < $DBSQL

info Done
